language: cpp

os: linux

dist: focal

jobs:
  include:
    # linux with default, builds native and bridges
    - os: linux
      compiler: gcc
      env:
        - TARGET="linux"

    # linux with macOS cross-compilation
    - os: linux
      compiler: gcc
      dist: trusty
      env:
        - TARGET="macos"

    # linux with win32 cross-compilation
    - os: linux
      compiler: gcc
      env:
        - TARGET="win32"

    # linux with win64 cross-compilation
    - os: linux
      compiler: gcc
      env:
        - TARGET="win64"

    # linux with gcc 8, strict build
    - os: linux
      compiler: gcc
      env:
        - TARGET="linux-strict"

    # linux with gcc 8, strict build, using juce
    - os: linux
      compiler: gcc
      env:
        - TARGET="linux-juce-strict"

    # linux with default, tests python code
    - os: linux
      compiler: gcc
      env:
        - TARGET="pylint"

before_install:
  - bash ${TRAVIS_BUILD_DIR}/.travis/before_install.sh

install:
  - bash ${TRAVIS_BUILD_DIR}/.travis/install.sh

script:
  - bash ${TRAVIS_BUILD_DIR}/.travis/script-${TARGET}.sh

notifications:
  email: true
  irc: "ircs://chat.libera.chat:7070/#kxstudio"
